### ISSUE TITLE
Wrong Import module

### ISSUE THREAD

**Issue by Shelf-A** [acaziasoftcom/react-native-bottomsheet#1]
This is a very handy bottom sheet because it support both iOS and Android but when importing you using import BottomSheet from 'react-native-bottom-sheet'; instead of import BottomSheet from 'react-native-bottomsheet';

Took me a long time to figure out what the problem was.

**Comment by Doko-Demo-Doa** [comment]
Thank you @Shelf-A I have fixed the docs, removed the redundant minus sign.
I didn't expect someone used this library (I built it for my internal team).

**Comment by Shelf-A** [comment]
I have been trying all bottom sheets I can find then I bumped into this one. I tried it and opened issues because you have a License file, btw thanks for that.
