### ISSUE TITLE
Have you looking into using Google bottomsheets implementation in Support library 23.2.0

### ISSUE THREAD

**Issue by wprater** [acaziasoftcom/react-native-bottomsheet#13]
Just curious, as I find the animation on this implementation to be a bit slow.

**Comment by Doko-Demo-Doa** [comment]
Well, as the description said. This is a port from bottomsheet native lib. I think I will expose the source code and let JavaScript-side control the animation speed.

**Comment by Dexwell** [comment]
+1 for using Google’s official support library implementation, would be really appreciated 🙏🏼 

The BottomSheet library itself suggests people use that instead, and is no longer maintained for that reason.

**Comment by Doko-Demo-Doa** [comment]
I have the similar thought.

But what do you expect from its feature, may I ask? Right now the lib is pretty simple (text only). Do you really want to use images as well?

**Comment by Dexwell** [comment]
I'd like the option to use icons yeah, although I like how it's almost a drop-in replacement for ActionSheetIOS. And that does not support images...
