### ISSUE TITLE
undefined is not an object evaluating '_reactNativeBottomsheet2.default.showBottomSheetWithOptions'

### ISSUE THREAD

**Issue by witalobenicio** [acaziasoftcom/react-native-bottomsheet#14]
I'm gettings this error when trying this on Android:

BottomSheet.showBottomSheetWithOptions({
      options: SORT_OPTIONS,
      title: Strings.Sort,
      dark: true,
      cancelButtonIndex: SORT_OPTIONS.length - 1,
    }, (value) => {
      this.sort(value);
    });

**Comment by witalobenicio** [comment]
BottomSheet is always undefined in Android.
react-native: 0.48
react: 16.0.0-alpha.12
react-native-bottomsheet: 1.8.1

**Comment by AndrejGajdos** [comment]
+1

**Comment by andrea-mosk** [comment]
news?

**Comment by Doko-Demo-Doa** [comment]
Have you linked it yet?

`react-native link react-native-bottomsheet`

**Comment by jarbitlira** [comment]
I fix this issue by adding the following code to **MainApplication.java**

```
import com.clipsub.rnbottomsheet.RNBottomSheetPackage; // Import this

....
@Override
protected List<ReactPackage> getPackages() {
  return Arrays.<ReactPackage>asList(
       new RNBottomSheetPackage() // Add this 
  );
}

```
I hope it help

**Comment by Doko-Demo-Doa** [comment]
Thank you, I will update the `README` file.

**Comment by mstfymrtc** [comment]
I still get this error although I linked as mentioned in README. Any solution?

**Comment by jarbitlira** [comment]
@mstfymrtc you have to do what i said in a comment above

**Comment by mstfymrtc** [comment]
MainApplication.java file already contain lines which you've written above.

**Comment by onmyway133** [comment]
In app build.gradle, add

```
compile project(':react-native-bottomsheet')
```

Then in MainApplication.java, add

```
import com.clipsub.rnbottomsheet.RNBottomSheetPackage;

new RNBottomSheetPackage()
```
