### ISSUE TITLE
Is there a 'cancel' callback function?

### ISSUE THREAD

**Issue by jpmasud** [acaziasoftcom/react-native-bottomsheet#15]
Hi there,

For me, the callback function works fine for the 'options' but the cancel button does not seem to be working. Is this intentional or am I doing something wrong?

```
BottomSheet.showBottomSheetWithOptions({
            options: this.props.options,
            cancelButtonIndex: this.props.cancelButtonIndex,
            destructiveButtonIndex: this.props.destructiveButtonIndex,
            title: this.props.title,
        }, (value) => {
            console.log(value);
        });
```

Props being passed in (in case something is wrong there):
```
interface IActionSheetProps {
    options: string[];
    cancelButtonIndex: number;
    destructiveButtonIndex: number;
    title: string;
}
```

**Comment by Doko-Demo-Doa** [comment]
What is your output? Can I see your `this.props.options` ?

**Comment by usrbowe** [comment]
I'm facing the same issue. The callback is not implemented for `Android`.
On `iOS`, since it's using native `ActionSheet`, it works as expected and callback get called even when `Cancel` button is pressed.

**Comment by usrbowe** [comment]
Create `PR` to fix this issue: https://github.com/acaziasoftcom/react-native-bottomsheet/pull/16
// cc: @jpmasud 
*Update:*
Fix released in version: `1.9.1`
https://github.com/acaziasoftcom/react-native-bottomsheet/commit/a130c79cd3b67780b3cd4d6ed8a87a0d58a656ed

**Comment by kholiavko-roman** [comment]
How to handle callback when I clicked outside a buttons ?  (just click on darkened screen of app) On android.
In this case BottomSheet hide but I need to call some actions on this.

**Comment by Doko-Demo-Doa** [comment]
Closing this issue because original ActionSheet does not have this implementation as well.
