### ISSUE TITLE
Broken release

### ISSUE THREAD

**Issue by ignatevdev** [acaziasoftcom/react-native-bottomsheet#17]
The latest version in npm (1.9.1) is broken.

The app crashes as soon as you select the value in the sheet with the following error in adb logs

`Illegal callback invocation from native module. This callback type only permits a single invocation from native code.`

The error occurs because RN allows the action press callback to be invoked only one time, but with the latest feature, which adds a callback invocation on cancel press, the callback gets executed twice, which causes a crash.

![image](https://user-images.githubusercontent.com/8458382/47162530-cac06c80-d2fc-11e8-9bb3-7ba8a6b92ec5.png)

For anyone stumbling across this - install version 1.8.1.

**Comment by usrbowe** [comment]
I tried to test with my code, and it works.
Can you share what version of RN you are using, with code example to test

**Update**:
- simulated the error too. Happens only when clicking on non-cancel btn.

**Comment by usrbowe** [comment]
@NSLS & @Doko-Demo-Doa 
Fixed the crash here: #18

**Comment by ignatevdev** [comment]
I'll test it out latet, thanks!
