### ISSUE TITLE
showBottomSheetWithOptions crashes the app

### ISSUE THREAD

**Issue by Shelf-A** [acaziasoftcom/react-native-bottomsheet#2]
Using showBottomSheetWithOptions crashes the app.
Tried the Example code:

     BottomSheet.showBottomSheetWithOptions({
              options: ['Option 1', 'Option 2', 'Option 3'],
              title: 'Demo Bottom Sheet',
              dark: true,
              cancelButtonIndex: 3,
            }, (value) => {
              alert(value);
     })

Using "react-native": "0.45.1"
          "react-native-bottomsheet": "^1.4.0",

**Comment by Doko-Demo-Doa** [comment]
Is this related to #1 ? I'm using it in my project and it works fine on both Android and iOS. Did you got crashes on iOS or Android?

**Comment by Shelf-A** [comment]
No it's not related to [#1](https://github.com/Clip-sub/react-native-bottomsheet/issues/1) 

For some reason, using title: 'Demo Bottom Sheet', crashes the app but if you change your title to anything other than 'Demo Bottom Sheet', it works fine. You can close this issue.
