### ISSUE TITLE
Android app getting crash on click of showImageMenu

### ISSUE THREAD

**Issue by VarshaJadhav** [acaziasoftcom/react-native-bottomsheet#24]
We're using:
"react": "16.8.3",
"react-native": "0.59.4",
"react-native-bottomsheet": "^1.8.1"

With all above defined versions, BottomSheet was working fine but suddenly we are getting following error on click of showImageMenu(i.e three dots ...) which opens options for edit, delete etc..
![Screenshot_20190807-130554](https://user-images.githubusercontent.com/20910346/62604351-85197280-b915-11e9-9efe-44fbed9132f5.png)

**Comment by yoginair** [comment]
?? please help ... ??

**Comment by sainsley123** [comment]
Getting the same error trying to view image picker on Android Pixel 2

**Comment by ArtemKolichenkov** [comment]
Just updating to version 2.0.1 resolved the issue for me.
