### ISSUE TITLE
RNBottomSheetPackage is not abstract and does not override abstract method createJSModules() in ReactPackage

### ISSUE THREAD

**Issue by pankaj-ag** [acaziasoftcom/react-native-bottomsheet#5]
"react": "16.0.0-alpha.6",
 "react-native": "0.44.0",
 "react-native-bottomsheet": "^1.6.0",

I am Facing this issue in Android.

**Comment by Doko-Demo-Doa** [comment]
Hi @pankaj-ag this is related to #4 , please use 1.5.0 for now. I will make another version with backward-compatible later.

**Comment by Doko-Demo-Doa** [comment]
New version updated, please update your package.
